services:
  floci:
    container_name: "${FLOCI_DOCKER_NAME:-floci-main}"
    image: hectorvent/floci:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
    volumes:
      - floci-data:/app/data
      - "/var/run/docker.sock:/var/run/docker.sock"



volumes:
  floci-data: {}
