name: ci


permissions:
  contents: read

on:
  push:
    paths-ignore:
      - 'guides/**'

jobs:
  ci:
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: '1.19.5-otp-28'
              otp: '28.4.1'

    runs-on: ubuntu-24.04

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit
          allowed-endpoints: >
            analytics.localstack.cloud:443
            assets.localstack.cloud:443
            auth.docker.io:443
            builds.hex.pm:443
            coveralls.io:443
            files.pythonhosted.org:443
            github.com:443
            httpbin.dev:443
            localstack.cloud:443
            production.cloudflare.docker.com:443
            pypi.org:443
            raw.githubusercontent.com:443
            registry-1.docker.io:443
            repo.hex.pm:443

      - name: Start Floci
        run: docker run -d -p 4566:4566 --name floci hectorvent/floci:latest

#      - name: Make bucket
#        run: |
#          AWS_ENDPOINT_URL=http://floci:4566 aws s3 mb s3://ex-ftp-test
#          AWS_ENDPOINT_URL=http://floci:4566 aws s3 ls

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: erlef/setup-beam@fc68ffb90438ef2936bbb3251622353b3dcb2f93 # v1.24.0
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{matrix.pair.elixir}}-${{matrix.pair.otp}}-

      - name: Run mix deps.get
        run: mix deps.get --only test

      - name: Run mix format
        run: mix format --check-formatted

      - name: Run mix deps.compile
        run: mix deps.compile

      - name: Run mix compile
        run: mix compile --warnings-as-errors

      - name: Run credo
        run: mix credo --strict

      - name: Run tests
        run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run dialyzer
        run: mix dialyzer

